version: '3'
services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    links:
      - "telnetjs:telnetjs"
    # TODO don't expose enCore.db to the nginx container
    volumes:
      - "./encore:/encore"
      - "./nginx/nginx.conf.template:/etc/nginx/nginx.conf"
    environment:
      WEBSOCKET_LISTEN_PORT: 8080
      NGINX_PORT: 4000
    command: ["/bin/sh", "-c", "\"envsubst /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'\""]
  lambdamoo:
    build: lambdamoo
    volumes:
      - "./encore:/encore"
    ports:
      - "7777:7777"
      - "7000:7000"
    entrypoint: ["./moo", "/encore/enCore.db", "/encore/enCore.db.new"]
  telnetjs:
    build: telnetjs
    links:
      - "lambdamoo:lambdamoo"
    environment:
      TCP_HOST: lambdamoo
      TCP_PORT: 7777
      WEBSOCKET_LISTEN_PORT: 8080

