version: '3'
services:
  nginx:
    image: nginx:1.21.0-alpine
    ports:
      - "80:80"
    links:
      - "telnetjs:telnetjs"
      - "lambdamoo:lambdamoo"
    volumes:
      - "./encore:/webroot/encore"
      - "./nginx/templates:/etc/nginx/templates/"
    environment:
      WEBSOCKET_HOST: telnetjs
      WEBSOCKET_PORT: 8080
      LAMBDAMOO_HOST: lambdamoo
      ENCORE_HTTP_PORT: 7000
      NGINX_PORT: 80
  lambdamoo:
    build: lambdamoo
    volumes:
      - "./encore:/encore"
    ports:
      - "7777:7777"
      - "7000:7000"
    entrypoint: ["./moo", "/encore/enCore.db", "/encore/enCore.db.new"]
  telnetjs:
    build: telnetjs
    links:
      - "lambdamoo:lambdamoo"
    environment:
      TCP_HOST: lambdamoo
      TCP_PORT: 7777
      WEBSOCKET_LISTEN_PORT: 8080

