version: '3'
services:
  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx
    ports:
      - "80:80"
    links:
      - "moo.js:moo.js"
      - "lambdamoo:lambdamoo"
    volumes:
      - "./encore:/webroot/encore"
      - "./nginx/templates:/etc/nginx/templates/"
    environment:
      WEBSOCKET_HOST: moo.js
      WEBSOCKET_PORT: 8080
      LAMBDAMOO_HOST: lambdamoo
      ENCORE_HTTP_PORT: 7000
      NGINX_PORT: 80
  lambdamoo:
    build: lambdamoo
    container_name: lambdamoo
    volumes:
      - "./encore:/encore"
    entrypoint: ["./moo", "/encore/enCore.db", "/encore/enCore.db.new"]
  moo.js:
    build: moo.js
    container_name: moo.js
    links:
      - "lambdamoo:lambdamoo"
    environment:
      TCP_HOST: lambdamoo
      TCP_PORT: 7777
      WEBSOCKET_LISTEN_PORT: 8080
      WEBSOCKET_HOST: '172.30.186.191'

