version: '3'
services:
  nginx:
    build:
      context: ./nginx
      args:
        ENABLED_MODULES: njs
    container_name: nginx
    ports:
      - "80:80"
      - "7000:7000"
    links:
      - "moo.js:moo.js"
      - "lambdamoo:lambdamoo"
    volumes:
      - "./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d/rewrite.js:/etc/nginx/conf.d/rewrite.js"
      - "./encore:/webroot/encore"
      - "./nginx/templates:/etc/nginx/templates/"
    environment:
      WEBSOCKET_HOST: moo.js
      WEBSOCKET_PORT: 8080
      LAMBDAMOO_HOST: lambdamoo
      ENCORE_HTTP_PORT: 7000
      NGINX_PORT: 80
      DOMAIN_NAME: localhost
      EXTERNAL_PROXY_PATH: external-proxy
      USE_HTTPS: "false"
  lambdamoo:
    build: lambdamoo
    container_name: lambdamoo
    volumes:
      - "./db:/db"
    entrypoint: ["./moo", "/db/enCore.db", "/db/enCore.db.new"]
  moo.js:
    build: moo.js
    container_name: moo.js
    links:
      - "lambdamoo:lambdamoo"
    environment:
      TCP_HOST: lambdamoo
      TCP_PORT: 7777
      WEBSOCKET_LISTEN_PORT: 8080
      WEBSOCKET_HOST: '172.30.186.191'

