version: '3'
services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    links:
      - "telnetjs:telnetjs"
    environment:
      WEBSOCKET_LISTEN_PORT: 8080
  lambdamoo:
    build: lambdamoo
    volumes:
      - "./encore:/encore"
    command: ["./moo", "enCore.db"]
  telnetjs:
    build: telnetjs
    links:
      - "lambdamoo:lambdamoo"
    environment:
      TCP_HOST: lambdamoo
      TCP_PORT: 7777
      WEBSOCKET_LISTEN_PORT: 8080

