#!/usr/bin/env expect

# Script to auto-configure the enCore database

set timeout 10
set prompt "\r\n(.*)\r\nMOO \\(#2\\): $"
set verbEditPrompt "(.*)Use \"\\.\" to end\\.\r\n$"

spawn ./moo -e enCore.db enCore.db.new

# Wait for initial prompt
expect -re "$prompt"

proc editObjectProperty {object property value} {
  variable prompt

  send ";$object.$property = \"$value\"\n"
  expect -re "$prompt"
}

proc editObjectVerb {object verb value} {
  variable prompt
  variable verbEditPrompt

  # Program the verb
  send "program #$object:$verb\n"
  expect -re "$verbEditPrompt"
  send "$value\n.\n"

  # Wait for the main MOO prompt
  expect -re "$prompt"
}

# Edit network-related properties
editObjectProperty "#72" "port" "$env(TCP_PORT)"
editObjectProperty "#72" "webport" "$env(ENCORE_HTTP_PORT)"
editObjectProperty "#72" "site" "$env(DOMAIN_NAME)"
editObjectProperty "#147" "external_baseurl" "http://$env(DOMAIN_NAME)/encore/"

# Return control to user
# interact

# Done!
send "quit\n"
expect -re "finished"
